

# MariaDB Database Configuration
db.url=jdbc:mysql://localhost:3306/pos?allowPublicKeyRetrieval=true&useSSL=false
db.user=javauser
db.password=root
db.driver=com.mysql.cj.jdbc.Driver

# if you wanna use MySQL, change the db.url to jdbc:mysql://localhost:3306/pos and make sure to have the MySQL Connector/J in your classpath instead of the MariaDB driver. 
# Also, update the db.driver to com.mysql.cj.jdbc.Driver if you switch to MySQL.
# or use whatever you used to create the database and user, make sure to change these values accordingly