

# MariaDB Database Configuration
db.url=jdbc:mariadb://localhost:3306/pos
db.user=javauser
db.password=root
db.driver=org.mariadb.jdbc.Driver

# or use whatever you used to create the database and user, make sure to change these values accordingly